Repository traveltechdeluxe/ash-rbac, pull requests merged in 2023-07, with the labels that each got.

#2 feat: prepare release 0.0.1
  logo.png
  mix.exs
  mix.lock
Labels: enhancement

#4 Update docs
  lib/ash_rbac.ex
Labels: chore

#3 Update README.md
  README.md
Labels: chore

#5 Add support for list of roles, string roles and fix "all fields" policies
  lib/ash_rbac.ex
  lib/ash_rbac/policies.ex
  test/ash_rbac_test.exs
  test/support/policy.ex
Labels: enhancement

#7 feat: add CHANGELOG
  CHANGELOG.md
Labels: chore

#8 fix: refactor checks
  CHANGELOG.md
  README.md
  config/config.exs
  documentation/getting_started.md
  documentation/relationships.md
  lib/ash_rbac/policies.ex
  mix.exs
  test/ash_rbac_test.exs
  test/support/api.ex
  test/support/calculation.ex
  test/support/child_resource.ex
  test/support/policy.ex
  test/support/registry.ex
  test/support/root_resource.ex
  test/support/shared_resource.ex
Labels: bug

#10 chore: prepare release 0.1.0
  CHANGELOG.md
  README.md
  documentation/getting_started.md
  mix.exs
Labels: chore

#11 fix: performance improvements
  CHANGELOG.md
  benchmarks/before/read.txt
  benchmarks/before/role_check.txt
  benchmarks/read.txt
  benchmarks/role_check.txt
  documentation/getting_started.md
  lib/ash_rbac/has_role.ex
  lib/ash_rbac/policies.ex
  mix.exs
  mix.lock
  samples/read.exs
  samples/role_check.exs
  test/ash_rbac_test.exs
Labels: enhancement

#15 feat: Adds support for other roles fields
  .formatter.exs
  lib/ash_rbac.ex
  lib/ash_rbac/has_role.ex
  lib/ash_rbac/policies.ex
  lib/ash_rbac/role.ex
Labels: enhancement

#17 fix: has role describe
  CHANGELOG.md
  lib/ash_rbac/has_role.ex
  mix.exs
Labels: bug

#18 fix: handle actor = nil in role check
  CHANGELOG.md
  lib/ash_rbac/has_role.ex
Labels: bug

#20 fix: do not add default forbid for custom policy fields
  CHANGELOG.md
  lib/ash_rbac/policies.ex
  test/ash_rbac_test.exs
  test/support/child_resource.ex
Labels: bug

#21 chore: prepare release 0.3.1
  CHANGELOG.md
  mix.exs
Labels: chore
